[package]
name = "rust-time-injection"
version = "0.1.0"
authors = ["Cyryl Płotnicki <cyplo@cyplo.net>"]

[dependencies]


[[bin]]
name = "function"
path = "src/function.rs"

[[bin]]
name = "stored-clock"
path = "src/stored_clock.rs"
